include ../lp015-respondself/Makefile

pcapupdate:
	cp ../lp043-parentM1/OUTPUT/parentM1.pcap parentM1.pcap


# Local Variables:
# compile: "make clean && make check"
# gdb-command: ""
# End Variables:
#
