# -*- makefile -*-
TESTNAME=rekeyikev2-inCR1
CONNNAME=parker1--jj2
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} /dev/null ../lp010-parentI2/parentR1.pcap ../lp013-parentI3/parentR2.pcap rekeyCR1.pcap
ENDNAME=parker

pcapupdate:
	cp ../lp047-rekeyikev2-R1/OUTPUT/rekeyikev2-R1.pcap rekeyCR1.pcap


