# this it the policy file that will be loaded
ENDNAME=h2h

# this is the policy that will be load
CONNNAME=mytunnel

TESTNAME=rekeyChildSA-fromR2

WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap ../lp037-h2hR1/h2hI1.pcap h2hI2.pcap

pcapupdate:
	cp ../lp038-h2hI2/OUTPUT/h2hI2.pcap .



