# -*- makefile -*-
TESTNAME=rekeyv2nopfs-I1
CONNNAME=parker1--jj2--nopfs
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} /dev/null ../lp010-parentI2/parentR1.pcap ../lp013-parentI3/parentR2.pcap
ENDNAME=parker

pcapupdate:
	@true
