# -*- makefile -*-
CONNNAME=parker
ENDNAME=jamesjohnson
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1PCAP=OUTPUT/nattR2.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} ${UNITTEST1PCAP} ../lp062-nattR1/nattI1.pcap nattI2.pcap

TESTNAME=nattR2

pcapupdate:
	cp ../lp063-nattI2/OUTPUT/nattI2.pcap nattI2.pcap




