# this it the policy file that will be loaded
ENDNAME=jamesjohnson

# this is the policy that will be load
CONNNAME=parker

TESTNAME=rekeyParentSA

WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap nattI1.pcap nattI2.pcap

pcapupdate:
	cp ../lp061-nattI1/OUTPUT/nattI1.pcap nattI1.pcap
	cp ../lp063-nattI2/OUTPUT/nattI2.pcap nattI2.pcap

